### ISSUE TITLE
Demo Projects Behind This Repo

### ISSUE THREAD

**Issue by ztianlin** [DeepVAC/deepvac#102]
Hi! Really appreciated for this work being available online. I tried to run DeepVAC/yolov5 project in your HomePod container. However, I found that the DeepVAC/yolov5 code seemed outdated with regard to this repo (The module abstraction were not the same, some classes' name and location were changed).  Do you have any plan to make demo projects in space DeepVAC up-to-date so that beginners can start learning DeepVAC easily? Many thanks.

**Comment by gemfield** [comment]
Thanks for pointing out this issue. The repo will get updated in this month per our schedule， please stay tuned.

**Comment by ztianlin** [comment]
Thanks again!
